% Analysing data output from b_symmetry_opt.pro

close all
rep1='/store/ASTRO/vs391/kinematic_dynamo/u_iii';
rep2='/store/ASTRO/vs391/kinematic_dynamo/u_abc';

box=[8 10 16 20 32];

files1=[{[rep1,'/b_sym_av_8.dat']}...
        {[rep1,'/b_sym_av_10.dat']}...
        {[rep1,'/b_sym_av_16.dat']}...
        {[rep1,'/b_sym_av_20.dat']}...
        {[rep1,'/b_sym_av_32.dat']} ];   

files2=[{[rep2,'/b_sym_av_8.dat']}...
        {[rep2,'/b_sym_av_10.dat']}...
        {[rep2,'/b_sym_av_16.dat']}...
        {[rep2,'/b_sym_av_20.dat']}...
        {[rep2,'/b_sym_av_32.dat']} ];  
    
LegendInfo = [     {'Box=[8,2,1]'}...
                    {'Box=[10,2,1]'}...
                    {'Box=[16,2,1]'}...
                    {'Box=[20,2,1]'}...
                    {'Box=[32,2,1]'}];     

for j=1:size(files1,2)
    full_file=importdata(files1{1,j});
    timevar=full_file;%.data;
    nvar=size(timevar,2);
    ndat=size(timevar,1);
    % Create a table with all variables
    %tblA = table(Lx,Rm,Gr,lBx,lBy,lBz);
    tblA = table(timevar(:,1),timevar(:,2), timevar(:,3),...
                timevar(:,4), timevar(:,5), timevar(:,6),...
                timevar(:,7));
    % Sort the rows of the table based on Rm
    tblB = sortrows(tblA,1); 
    Rm  = tblB{:,1};
    mdx = tblB{:,2};
    mdy = tblB{:,3};
    mdz = tblB{:,4};
    ix  = tblB{:,5};
    iy  = tblB{:,6};
    iz  = tblB{:,7}; 
    
    hFig = figure(1);
    set(hFig, 'Position', [100, 50, 1100, 500]); 
    subplot(3,5,[j,j+5])
        p1 = plot(Rm,mdx, 'o',...
            'LineStyle', 'none',...
            'color','b',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'b', ...
            'MarkerFaceColor', 'b', ...
            'MarkerSize',4.5,...
            'DisplayName','B_x'); 
            title(LegendInfo{j})
            if (j==1)
                ylabel('B^I-B^{II} / B^I+B^{II}')
            end
            xlim([0.1 35])
ylim([1e-4 20])
        hold on;
        p2 = plot(Rm,mdy, 'o',...
            'LineStyle', 'none',...
            'color','r',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'r', ...
            'MarkerFaceColor', 'r', ...
            'MarkerSize',4.5,...
            'DisplayName','B_y'); 
        p3 = plot(Rm,mdz, 'o',...
            'LineStyle', 'none',...
            'color','k',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'k', ...
            'MarkerFaceColor', 'k', ...
            'MarkerSize',4.5,...
            'DisplayName','B_z'); 
         if (j==5)
            legend([p1 p2 p3],  'Location', 'northeast')
         end
        plot([1e-4 1e2],[1 1],'k:')
    subplot(3,5,10+j)
        semilogx(Rm,ix/6.28, 'o',...
            'LineStyle', 'none',...
            'color','b',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'b', ...
            'MarkerFaceColor', 'b', ...
            'MarkerSize',4.5,...
            'DisplayName','B_x'); 
            xlabel('R_m')
            if (j==1)
                ylabel('x_0')
            end
            xlim([0.1 35])
       
        hold on;
        plot(Rm,iy/6.28, 'o',...
            'LineStyle', 'none',...
            'color','r',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'r', ...
            'MarkerFaceColor', 'r', ...
            'MarkerSize',4.5,...
            'DisplayName','B_y'); 
        plot(Rm,iz/6.28, 'o',...
            'LineStyle', 'none',...
            'color','k',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'k', ...
            'MarkerFaceColor', 'k', ...
            'MarkerSize',4.5,...
            'DisplayName','B_z')



end



for j=1:size(files2,2)
    full_file=importdata(files2{1,j});
    timevar=full_file;%.data;
    nvar=size(timevar,2);
    ndat=size(timevar,1);
    % Create a table with all variables
    %tblA = table(Lx,Rm,Gr,lBx,lBy,lBz);
    tblA = table(timevar(:,1),timevar(:,2), timevar(:,3),...
                timevar(:,4), timevar(:,5), timevar(:,6),...
                timevar(:,7));
    % Sort the rows of the table based on Rm
    tblB = sortrows(tblA,1); 
    Rm  = tblB{:,1};
    mdx = tblB{:,2};
    mdy = tblB{:,3};
    mdz = tblB{:,4};
    ix  = tblB{:,5};
    iy  = tblB{:,6};
    iz  = tblB{:,7}; 
    
    hFig = figure(2);
    set(hFig, 'Position', [100, 50, 1100, 500]); 
    subplot(3,5,[j,j+5])
        p1 = plot(Rm,mdx, 'o',...
            'LineStyle', 'none',...
            'color','b',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'b', ...
            'MarkerFaceColor', 'b', ...
            'MarkerSize',4.5,...
            'DisplayName','B_x'); 
            title(LegendInfo{j})
            if (j==1)
                ylabel('B^I-B^{II} / B^I+B^{II}')
            end
            xlim([0.1 35])
            ylim([1e-4 20])
        hold on;
        p2 = plot(Rm,mdy, 'o',...
            'LineStyle', 'none',...
            'color','r',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'r', ...
            'MarkerFaceColor', 'r', ...
            'MarkerSize',4.5,...
            'DisplayName','B_y'); 
        p3 = plot(Rm,mdz, 'o',...
            'LineStyle', 'none',...
            'color','k',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'k', ...
            'MarkerFaceColor', 'k', ...
            'MarkerSize',4.5,...
            'DisplayName','B_z'); 
        if (j==5)
            legend([p1 p2 p3],  'Location', 'northeast')
        end
        plot([1e-4 1e2],[1 1],'k:')
    subplot(3,5,10+j)
        semilogx(Rm,ix/6.28, 'o',...
            'LineStyle', 'none',...
            'color','b',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'b', ...
            'MarkerFaceColor', 'b', ...
            'MarkerSize',4.5,...
            'DisplayName','B_x'); 
            xlabel('R_m')
            if (j==1)
                ylabel('x_0')
            end
            xlim([0.1 35])
        
        hold on;
        plot(Rm,iy/6.28, 'o',...
            'LineStyle', 'none',...
            'color','r',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'r', ...
            'MarkerFaceColor', 'r', ...
            'MarkerSize',4.5,...
            'DisplayName','B_y'); 
        plot(Rm,iz/6.28, 'o',...
            'LineStyle', 'none',...
            'color','k',...
            'LineWidth',1.5,...
            'MarkerEdgeColor', 'k', ...
            'MarkerFaceColor', 'k', ...
            'MarkerSize',4.5,...
            'DisplayName','B_z')



end
