close all;
file_info=['~/Dropbox/PhD/matlab/rm_tran.txt'];
full_file=importdata(file_info);
info=full_file;
tblA = table(info(:,1),info(:,2), info(:,3), info(:,4),info(:,5), info(:,6), info(:,7));
box             = tblA{1:end,1};
R_mtr_III       = tblA{1:end,2};
R_mtr_abc		= tblA{1:end,3};
L_largeB_III	= tblA{1:end,4};
L_largeB_abc	= tblA{1:end,5};
L_smallB_III	= tblA{1:end,6};
L_smallB_abc    = tblA{1:end,7};

color{1}=[0.83 0.17 0.17];  %abc
color{2}=[0 0 0];           %iii

hFig = figure(1);
set(hFig, 'Position', [100, 50, 600, 400]); 
    subplot(1,2,1)
            p1= plot(box,R_mtr_abc,'o', ...
                'LineStyle', ':',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',3.5,...
                'DisplayName','u_{abc}'); 
                hold on;
                xlabel('Aspect Ratio')
                ylabel('R_m^{tran}')
                ylim([0 14])
            p2= plot(box,R_mtr_III,'o', ...
                'LineStyle', ':',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',3.5,...
                'DisplayName','u_{III}');      
            legend([p1 p2])%,'Location','west')
       subplot(1,2,2)
            p1= plot(box,L_largeB_abc,'o', ...
                'LineStyle', ':',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',3.5,...
                'DisplayName','E_m^{L} > E_m^{S} '); 
                hold on;
                xlabel('Aspect Ratio')
                ylabel('Scaling power of R_m')
                ylim([-1 0])
            p2= plot(box,L_largeB_III,'o', ...
                'LineStyle', ':',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',3.5,...
                'DisplayName','E_m^{L} > E_m^{S}');           
            p3= plot(box,L_smallB_abc,'s', ...
                'LineStyle', ':',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',3.5,...
                'DisplayName','E_m^{L} > E_m^{S}'); 
                hold on;
                xlabel('Aspect Ratio')
                ylabel('Scaling power of R_m')
                
            p4= plot(box,L_smallB_III,'s', ...
                'LineStyle', ':',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',3.5,...
                'DisplayName','E_m^{L} > E_m^{S}');
            legend([p1 p2 p3 p4])