%for iii=0:21   % u_iii
%for iii=1:15     % u_abc
for iii=1:1
   
    rep=['~/Dropbox/'];
    %file_time=[rep, '/timevar'];%,num2str(iii)];
    
    %rep=['/local/scratch/public/public/Dropbox/'];
    file_time=[rep, '/timevar',num2str(iii)];
    full_file=importdata(file_time);
    timevar=transpose(full_file.data);
    nvar=size(timevar,1);
    var_name=strread(full_file.textdata{1},'%s',nvar);

    % ASSIGN VARIABLE WITH HEADINGS 
    for ii=1:nvar
        assignin('base',var_name{ii},timevar(ii,:)); 
    end
    color{1}=[0.83 0.17 0.17];
    color{2}=[0 0 0];
    
    %%%%%%%%%%
    %% PLOT %%
    %%%%%%%%%%
    hFig = figure(iii+1);
    set(hFig, 'Position', [100, 50, 1100, 500]); 
        subplot(2,5,1:4)
            p1= semilogy(t,em, ...
                'LineStyle', '-',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',1.5,...
                'DisplayName','E_m'); 
            ylim([min(em(end),ev(end))*0.8 max(em(end),ev(end))*1.2])
            title(['R_e=', num2str(Re(end)),'        R_m=', num2str(Rm(end))]);
            hold on;
            p2= semilogy(t,ev, ...
                'LineStyle', '-',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',1.5,...
                'DisplayName','E_k');
            legend([p1 p2],'Location','west')
            plot([t(1) t(end)],[em(end) em(end)],'k:');
            plot([t(1) t(end)],[ev(end) ev(end)],'k:');
        subplot(2,5,5)    
            plot(t,em./ev, ...
                'LineStyle', '-',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',1.5);
                title('E_m/E_k'); 
        subplot(2,5,6)
            p3= plot(t,w2, ...
                'LineStyle', '-',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',1.5);
                title('Enstrophy');  

         subplot(2,5,7)
            p4= plot(t,hv, ...
                'LineStyle', '-',...
                'color',color{2},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{2}, ...
                'MarkerFaceColor', color{2}, ...
                'MarkerSize',1.5);  
                title('Kinetic Helicity');

        subplot(2,5,8)
            p5= plot(t,hc, ...
                'LineStyle', '-',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',1.5);
                title('Cross Helicity');  

         subplot(2,5,9)
            p6= plot(t,hm, ...
                'LineStyle', '-',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',1.5);
                title('Magnetic Helicity');
        subplot(2,5,10)
            p6= plot(t,hm - hv, ...
                'LineStyle', '-',...
                'color',color{1},...
                'LineWidth',1.5,...
                'MarkerEdgeColor', color{1}, ...
                'MarkerFaceColor', color{1}, ...
                'MarkerSize',1.5);
                title('Residual Helicity');
end